apiVersion: v1
kind: Service
metadata:
  name: hoppang-web
  namespace: hoppang
spec:
  selector:
    app: hoppang-web
  type: NodePort
  ports:
    - port: 10244
      targetPort: 10244
      nodePort: 30044
